wppconnect-team/wppconnect

src/lib/wapi/functions/get-chat-by-id.js

Correção nos metodos sendImage e sendFile, ambos estavam retornando id da mensagem anterior como resposta.

Correção ao obter id ao enviar mensagens de midia

---

src/api/layers/host.layer.ts
src/config/create-config.ts

append to options of WPPConfig for working with wa-js, but not work. What must I change?

feat: options for GA and linkPreviewApiServers

---

docs/getting-started/creating-client.md
examples/bot-functions/index.js
src/api/layers/host.layer.ts
src/api/model/initializer.ts
src/controllers/browser.ts
src/controllers/initializer.ts

It will help a lot of people who need this whatsapp screen status.
When the screen is loading, the callback function 'onLoadingScreen' is called with two parameters:
percent: number
message: string
To test (it takes a while): `npm install github:tonbotfy/wppconnect`
**_wppconnect
.create({
session: 'teste',
onLoadingScreen: (percent, message) => {
console.log('LOADING_SCREEN', percent, message);
},
})_**

feat: Loading Screen callback function with percent and message

---

src/api/layers/host.layer.ts
src/controllers/browser.ts

A função estava sendo chamada antes do WAPI ser carregado no browser, então, em alguns momentos ocasionava erro de WAPI no WppConnect-Server

fix: Fixed WAPI is not defined (fix wppconnect-team/wppconnect-server#864)

---

src/api/layers/host.layer.ts

Fixes #1335.
When the whatsweb page load with a token already set, it's look like the page.on('load') is firing before the event is set

fix: page on load order

---

package.json
src/api/helpers/evaluate-and-return.ts
src/api/layers/sender.layer.ts
src/controllers/auth.ts
src/types/Evaluate.d.ts

Fixes # .
No primeiro comit corrigi os tipos de retorno do Puppeteer que bloqueavam a build da LIB, à partir da versão 14.4.1 do Pupeteer foi excluido a exporação dos tipos e são auto-deduzidos, para manter a mesma função, copiei os tipos do código original do Pupeteer, e coloquei o retorno seguindo o mesmo padrão desse PR: https://github.com/puppeteer/puppeteer/pull/8547
No segundo comit é a correção de erro que dava undefined no retorno da mensagem, ao enviar uma Lista.
-
-
To test (it takes a while): `npm install github:icleitoncosta/wppconnect#<branch>`

fix: Fixed Puppeteer error and undefined sendList

---

src/controllers/browser.ts

This commit reverts to a previous fix as a temporary workaround. The issue encountered on CentOS7 and Debian11 when using the 'new' mode in Puppeteer's headless mode requires further investigation and a more comprehensive solution. By reverting to the previous fix, we aim to restore functionality and address the immediate problem. Future updates will address the underlying issue appropriately.

fix: Reverting to previous fix as a temporary workaround

---

src/api/model/enum/message-type.ts

Fixes # .
-
-
The poll_creation label to message types are missing, this PR just create this message type.

feat: add poll_creation to message types

---

src/controllers/initializer.ts

Fixes #2109 
Bypass recent Content-Security-Policy restrictions on recent WhatsApp Web versions.
To test (it takes a while): `npm install github:renandecarlo/wppconnect#renandecarlo-patch-1`

fix: Bypass content-security-policy errors

---

docs/getting-started/basic-functions.md
docs/getting-started/configuring-logger.md
docs/getting-started/creating-client.md
docs/getting-started/receiving-messages.md

Fixes #2188. as described there, using the code like this results ina `ReferenceError: start is not defined`
Also removed a few typos and grammar mistakes. Disclaimer: I'm not a native speaker.
I also saw `Brazil` being spelled as `Brasil` [here](https://wppconnect.io/docs/tutorial/basics/basic-functions#sendlocation) but that could be intentional. If countries need to be specified in English, then it would have to be `Brazil`. Not sure what the API requires.

doc(#2188): invalid start client command in the documentation

---

src/api/model/message.ts

Boas,
the message body field is optional: For example you may try to access it as part of the message when removing/adding someone from/to a group.
Reproduction: Receive a message during `onMessage`, access the `body` field, convert it to lowercase for further processing, and you would experience this error: `[sessionName:client] TypeError: Cannot read properties of undefined (reading 'toLowerCase')`

fix: error when accessing message body during notifications

---

src/api/layers/listener.layer.ts
src/api/model/contact.ts
src/api/model/incoming-call.ts
src/api/model/index.ts

It's typed based on what I know and the data I received in a testing call. Let me know if there is anything I can improve. I left `participants` as an `any` array because I wasn't sure if there will be contact objects or only IDs.

feat: added type definitions for incoming calls

---

docs/getting-started/configuring-logger.md
docs/getting-started/installation.md
docs/getting-started/receiving-messages.md
examples/basic/index.js
examples/bot-functions/index.js
examples/newsletter/index.js
examples/orders/index.js

- not sure if I translated `Jen` correctly as "jeans"
- Yarn installation example added since it is a fairly common package manager

doc: translated example code

---

src/api/layers/profile.layer.ts

I tested it in the browser only:
```js
WPP.profile.setMyProfileName("something")
Promise {<pending>}
WPP.profile.getMyProfileName()
'something'
```
It should not need to be a promise apparently

feat: added a profile name getter method

---

src/api/model/contact.ts

From what I observed, this is a string (serialized format, user@server). If there are exceptions where it is actually a `WID` object, let me know and I'll adapt this PR.

fix: ID type definition of Contact model

---

src/api/model/message.ts

Where I saw `null`, I assumed there could be other values so I added comments as a reminder to specify this later.
I have not seen `labels` in any messages, maybe it is already gone instead of just deprecated, so I marked it as optional.

fix: added missing properties to the Message type definition

---

docs/getting-started/basic-functions.md

Fixes #2198 .
Updated it to no longer feature the deperecated `reply()` method.
Partially untested.
Question:
What is `sendMessageOptions` good for? It has a signature similar to `sendText` (but less strongly typed). Should it be deprecated?
```typescript
sendText(to: string, content: string, options?: TextMessageOptions): Promise<Message>;
sendMessageOptions(chat: any, content: any, options?: any): Promise<Message>;
```

docs: updated examples using the outdated reply method

---

src/api/layers/ui.layer.ts

Base layer for comparison: https://github.com/wppconnect-team/wa-js/blob/4df7fee17ed071b461e2da28d8e6c9e7592c9739/src/chat/functions/getActiveChat.ts#L33 (it's not `async` there)
Tested in the browser, there is no difference:
It's surely difficult to keep both layers (wa-js/wppconnect) in sync. Have you considered consolidating them into one repo?

fix: getActiveChat is not async

---

src/api/model/group-metadata.ts

When there is no parent group, it contains `undefined`:

fix: parent group Id missing in group metadata

---

src/api/layers/retriever.layer.ts

here we can see that wa-js supports it: https://github.com/wppconnect-team/wa-js/blob/3de60b73890494107addb4c979ede488f1278c8e/src/chat/functions/get.ts#L25
let me link this to #2350 because it's the same topic: WPPCOnnect and wa-js are not in sync

fix: getChatById also accepts a Wid as input param

---

src/api/layers/sender.layer.ts

relates to https://github.com/wppconnect-team/wa-js/pull/2391

fix: enhanced type definition for recipients of the sendFile method

---

src/api/model/message.ts

This pull request resolves the issue where the `isViewOnce` field was missing in the `Message` type definition, although it was present in the message's JSON response. The field is now correctly included in the type, allowing for proper handling of media files (video, image, or audio) where `isViewOnce` is expected.
When the file is not a media type, the `isViewOnce` field remains undefined, as intended.
Closes #2358

fix: add 'isViewOnce' in message interface

---

src/api/layers/host.layer.ts
src/config/create-config.ts
src/controllers/browser.ts

- Added support for proxy authentication when connecting to the repository using `wppconnect`.
- Proxy configuration includes:
- Proxy URL
- Username for authentication
- Password for authentication
- Updated the connection flow to support proxy configuration as part of the `.create()` method in `wppconnect`.
```js
wppconnect
.create({
proxy: {
url: 'http://proxy.example.com',
username: 'username',
password: 'password',
},
})
.then((client) => start(client))
.catch((error) => {
console.log(error);
});
```
This new functionality allows users to connect to the repository through a secure proxy, enabling better access control and security in environments requiring a proxy connection. The provided example demonstrates how to configure and use the proxy within the application.

feat: Proxy authentication

---

src/api/layers/host.layer.ts
src/api/layers/listener.layer.ts
src/api/model/get-messages-param.ts
src/api/model/initializer.ts
src/api/whatsapp.ts

docs: typos / grammar corrections

---

src/api/layers/group.layer.ts
src/api/model/chat.ts
src/api/model/group-metadata.ts

They might be optional for other types of chats as I spotted them on the chat objects of groups.

fix: added missing group chat properties

---

src/api/model/chat.ts

I noticed that for **some** chats, this attribute is `undefined`. To reproduce, open some chats and try the following snippets:
indicator that the chat is (still) open:
```js
WPP.chat.getActiveChat()
b {revisionNumber: 36, __x_stale: {…}, __fired: null, __changes: null, __initialized: true, …}
```
to check for presence of the spam detection flag:
```js
WPP.chat.getActiveChat().notSpam
undefined
```
Not sure why WhatsApp does this. ☹️

fix: notSpam attribute of Chat is optional

---

src/api/model/enum/group-notification-type.ts

I received this new GP2 event subtype shortly/immediately after joining a group though an invitation link, so I suspect it does not actually refer to the group's initial creation:
```
{
id: 'false_[REDACTED]-1570181234@g.us_[REDACTED]create_[REDACTED]',
viewed: false,
body: 'Lorem ipsum',
type: 'gp2',
subtype: 'create',
t: 1570181234,
from: '[REDACTED]-1570181234@g.us',
isNewMsg: true,
star: false,
kicNotified: false,
recvFresh: true,
isFromTemplate: false,
pollInvalidated: false,
isSentCagPollCreation: false,
latestEditMsgKey: null,
latestEditSenderTimestampMs: null,
recipients: [],
mentionedJidList: [],
groupMentions: [],
isEventCanceled: false,
eventInvalidated: false,
isVcardOverMmsDocument: false,
isForwarded: false,
hasReaction: false,
productHeaderImageRejected: false, …
```

feat: new notification subtype (group creation)
