src/api/layers/sender.layer.ts
=> feat: Added sendPtt from file

src/config/create-config.ts, src/controllers/browser.ts, src/controllers/initializer.ts
- Allow pass browser/page in create method
To test (it takes a while): `npm install github:wppconnect-team/wppconnect#create_browser`
=> feat: Allow pass browser/page in create method

src/controllers/welcome.ts
Fixes # .
- the message displayed as an update instruction has the wrong package name
- the correct command should be: npm update @wppconnect-team/wppconnect
=> Fix: corrects update instructions

package-lock.json, package.json, src/api/helpers/evaluate-and-return.ts, src/api/layers/controls.layer.ts, src/api/layers/group.layer.ts, src/api/model/enum/group-property.ts, src/api/model/enum/index.ts, src/api/whatsapp.ts, src/lib/wapi/functions/index.js, src/lib/wapi/functions/set-group-description.js, src/lib/wapi/functions/set-group-property.js, src/lib/wapi/functions/set-group-subject.js, src/lib/wapi/functions/set-temporary-messages.js, src/lib/wapi/store/store-objects.js, src/lib/wapi/wapi.js, src/types/WAPI.d.ts, tsconfig.json
Fixes #131, #133
- Added options to edit group description, subject and properties
- Added function to enable and disable temporary messages
=> Added options to edit group description, subject and properties

.gitignore, src/api/helpers/evaluate-and-return.ts, src/api/layers/business.layer.ts, src/api/whatsapp.ts, src/lib/wapi/business/get-business-profiles-products.js, src/lib/wapi/business/get-order-by-msg.js, src/lib/wapi/business/index.js, src/lib/wapi/wapi.js, src/types/WAPI.d.ts
=> feat: new functions catalog business

examples/rest/README.md, examples/rest/index.js
Implementação de um código de exemplo para consumir a Lib via REST
=> docs: Exemplo de código para consumir a lib via REST

examples/bot-functions/index.js
=> docs: exemple to use buttons

src/api/layers/host.layer.ts, src/lib/wapi/functions/get-wid.js, src/lib/wapi/functions/index.js, src/lib/wapi/serializers/serialize-profilePic.js, src/lib/wapi/wapi.js, src/types/WAPI.d.ts
…rupo ou contato
Correção para obter foto de perfil do grupo ou contato. A falha só ocorre quando se tenta obter fotos de contatos ou grupos que não estão em cache
Fixes # .
-
-
=> fix(getProfilePicFromServer): Correção para obter foto de perfil do grupo ou contato, feat(getWid) Obter o wid da sessão conectada

src/lib/wapi/listeners/init-listeners.js
Refs: #422
Fixes #422 .
Add delay while body promise is not resolved
To test (it takes a while): `npm install github:ghsgabriel/wppconnect#fix_first_message_from_new_contact`
=> fix: The first contact number cannot receive the first message

src/config/create-config.ts
=> fix: ajuste versao default para 2.2204

src/api/model/chat.ts, src/api/model/group-metadata.ts
Fix typing.
Add correct typing over given location
To test (it takes a while): `npm install github:viniciusgdr/wppconnect#master`
=> fix(typings): Added correct typing of GroupMetadata and Chat

src/api/layers/listener.layer.ts
Fixes # .
Novo evento para Adicionar onReactionMessage
-
-
To test (it takes a while): `npm install github:@icleitoncosta/wppconnect#feat/onReactionMessage`
=> feat: Added onReactionMessage event

src/api/layers/labels.layer.ts
=> fix: getAllLabels return null

src/api/layers/catalog.layer.ts, src/api/layers/labels.layer.ts, src/api/layers/retriever.layer.ts, src/api/layers/sender.layer.ts, src/api/layers/status.layer.ts
=> Export funcs

README.md
=> docs(readme): fix link to the documentation

src/token-store/fileTokenStore.ts, src/token-store/memoryTokenStore.ts
Fix TS2416 error on dist build, simple change in files:
• src/token-store/fileTokenStore.d.ts:66
• src/token-store/memoryTokenStore.d.ts:27
Error:
=> fix: Fix TS2416 error on dist build

src/api/layers/listener.layer.ts, src/api/layers/retriever.layer.ts
=> feat: Added onPollResponse event

package.json
This is a momentary fix. Is necessary upgrade de core of docs.
=> fix: Fixed error typedoc version

src/api/layers/group.layer.ts, src/api/layers/host.layer.ts, src/api/layers/profile.layer.ts, src/api/layers/ui.layer.ts
The things that should be added through this Pull Request are:
=> New features

.eslintrc.js, src/api/whatsapp.ts
Fixes # .
-inclusion of function to screenshot current page in whatsapp.ts
-endOfLine: auto in eslintrc.js
=> inclusion of function to screenshot current page

src/api/layers/catalog.layer.ts, src/api/layers/community.layer.ts
=> feat: Added community functions

src/config/create-config.ts
=> fix: Fixed version default for 2.2346

src/lib/wapi/wapi.js
=> feat: Added  sendTextStatus functions

src/lib/wapi/wapi.js
=> feat: Added deleteOldChats functions

package.json, src/api/layers/host.layer.ts
=> fix: Fixed build and start mistakes (close #1911)

src/api/layers/controls.layer.ts
=> feat: Added EditMessage method

package.json
=> chore: Downgrade sharp to maintain compatibility

src/api/layers/group.layer.ts
=> fix: Fixed removeParticipant return (close #1709)

src/api/layers/status.layer.ts
=> feat: Added support to options in send status (close #1855)

src/api/layers/host.layer.ts, src/api/model/initializer.ts, src/config/create-config.ts, src/controllers/initializer.ts
Added support for login by code in whatsapp
=> feat: Added support to login by code (close #1921)

src/config/create-config.ts
=> fix: Upgrade default whatsapp version

src/api/layers/host.layer.ts, src/config/create-config.ts, src/controllers/browser.ts
Fixes # .
-
-
To test (it takes a while): `npm install github:wppconnect-team/wppconnect#wapi2`
=> test: Fixed WAPI is not defined

src/api/layers/retriever.layer.ts
=> fix: Fixed error on checkNumberStatus

src/api/layers/sender.layer.ts, src/api/whatsapp.ts
Fixes #2242
Pls also critically check if my translations are correct.
=> doc: enhanced base64 image-related JSDOC sections

src/api/layers/ui.layer.ts
=> feat: method to close opened chats (#2271)

src/api/layers/profile.layer.ts
=> feat: profile status getter method
